mode = "dark"
accent = "#78b4ff"
selection = "#25486e"
muted = "#adb0b9"
background = "#1c1e24"
dark_background = "#17191f"
darker_background = "#111318"
lighter_background = "#2d3038"
foreground = "#f2f3f5"
dark_foreground = "#b6b8c1"
light_foreground = "#d9dbe1"
bright_foreground = "#ffffff"
red = "#ff827a"
yellow = "#e8c66a"
orange = "#ffae70"
green = "#86d39b"
cyan = "#7dd7dc"
blue = "#78b4ff"
magenta = "#c7a0ef"
brown = "#c9a58c"
bright_red = "#ffa19b"
bright_yellow = "#f5db8c"
bright_green = "#a0e6b2"
bright_cyan = "#9ce7eb"
bright_blue = "#a1ccff"
bright_magenta = "#dec0ff"
hyprland_active_border = "rgba(78b4ffbb)"
hyprland_inactive_border = "rgba(ffffff22)"
